# Generated by Django 4.2.23 on 2025-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("date", models.DateField()),
                ("subject", models.CharField(max_length=50)),
                ("marks", models.FloatField()),
                ("out_of", models.FloatField()),
                (
                    "r_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "subject")},
            },
        ),
    ]
